export type Lang = "fr" | "en" | "ar";

export const LANGS: { code: Lang; label: string; short: string; dir: "ltr" | "rtl" }[] = [
  { code: "fr", label: "Français", short: "FR", dir: "ltr" },
  { code: "en", label: "English", short: "EN", dir: "ltr" },
  { code: "ar", label: "العربية", short: "AR", dir: "rtl" },
];

/**
 * Coordonnées du cabinet — données de démonstration, à remplacer par les
 * informations officielles. `demo: true` drives the honesty guardrails in the
 * contact form and the footer disclaimers; flip it once real data is loaded.
 */
export const CABINET = {
  demo: true,
  /** Canonical origin, used for hreflang/canonical/sitemap at build time. */
  siteUrl: "https://www.cabinet-majdoub.tn",
  lawyer: "Brahim Majdoub",
  honorific: "Maître",
  phoneDisplay: "+216 98 412 763",
  phone: "+21698412763",
  landlineDisplay: "+216 71 340 118",
  landline: "+21671340118",
  whatsapp: "21698412763",
  email: "contact@cabinet-majdoub.tn",
  facebook: "https://www.facebook.com/brahim.majdoub.7/",
  facebookHandle: "/brahim.majdoub.7",
  mapEmbed: "https://www.google.com/maps?q=Avenue+Habib+Bourguiba+Tunis&hl=fr&z=15&output=embed",
  mapLink: "https://www.google.com/maps/search/?api=1&query=Avenue+Habib+Bourguiba+Tunis",
};

const fr = {
  seo: {
    title: "Maître Brahim Majdoub — Avocat au Barreau de Tunis",
    description:
      "Cabinet de Maître Brahim Majdoub, avocat inscrit au Barreau de Tunis (Tunisie). Droit des sociétés, statut personnel, immobilier, droit du travail, pénal des affaires, recouvrement de créances et voies d'exécution. Conseil préventif, négociation et plaidoirie — honoraires convenus par écrit.",
  },
  brand: {
    name: "Brahim Majdoub",
    initials: "BM",
  },
  a11y: {
    skip: "Aller au contenu principal",
    menu: "Ouvrir le menu",
    close: "Fermer le menu",
    lang: "Choisir la langue du site",
    map: "Localisation du cabinet sur Google Maps",
    facebook: "Page Facebook du cabinet",
    whatsapp: "Contacter le cabinet sur WhatsApp",
    email: "Écrire un e-mail au cabinet",
    phone: "Appeler le cabinet",
    top: "Revenir en haut de la page",
    nav: "Navigation principale",
  },
  nav: {
    about: "Le cabinet",
    expertise: "Domaines",
    method: "Méthode",
    career: "Parcours",
    testimonies: "Avis",
    faq: "FAQ",
    contact: "Contact",
    book: "Demander un rendez-vous",
    call: "Appeler",
  },
  utility: "Ordre National des Avocats de Tunisie — Barreau de Tunis",
  hero: {
    eyebrow: "Avocat au Barreau de Tunis — Tunisie",
    titleTop: "L'art de la",
    titleEm: "Défense",
    lead: "Avocat inscrit au Barreau de Tunis, j'accompagne particuliers, sociétés et investisseurs devant les juridictions tunisiennes : conseil préventif, négociation et plaidoirie — honoraires convenus par écrit, information continue.",
    ctaPrimary: "Demander un rendez-vous",
    ctaSecondary: "Présentation du cabinet",
    portraitCaption: "Maître Brahim Majdoub",
    portraitRole: "Avocat au Barreau de Tunis",
    credentials: [
      { k: "Barreau", v: "Tunis — ONAT" },
      { k: "Juridictions", v: "Tunis · Sousse · Sfax · Djerba" },
      { k: "Langues", v: "Arabe · Français · Anglais" },
    ],
  },
  stats: {
    eyebrow: "Le cabinet en chiffres",
    items: [
      { value: 12, suffix: "+", label: "années d'exercice" },
      { value: 850, suffix: "+", label: "dossiers suivis" },
      { value: 6, suffix: "", label: "domaines d'intervention" },
      { value: 24, suffix: "h", label: "délai de réponse" },
    ],
  },
  about: {
    eyebrow: "01 — Le cabinet",
    title: "Un avocat de contentieux et de",
    titleEm: "conseil.",
    lead: "Une méthode exigeante : étude préliminaire écrite, honoraires convenus à l'avance, compte rendu après chaque audience.",
    p1: "Inscrit au tableau de l'Ordre National des Avocats de Tunisie, je conseille et défends particuliers, sociétés et investisseurs. Mon parcours en droit privé et en droit des affaires a forgé une pratique fondée sur la maîtrise de la procédure, la précision rédactionnelle et le respect des délais annoncés.",
    p2: "J'interviens devant les tribunaux de première instance, les cours d'appel, la Cour de cassation, ainsi qu'en matière pénale et devant les instances d'arbitrage. Chaque dossier fait l'objet d'une convention écrite précisant la mission, le calendrier prévisionnel et l'honoraire — sans engagement d'aucune sorte avant votre accord.",
    bullets: [
      "Étude préliminaire écrite de chaque dossier",
      "Convention d'honoraires signée avant toute diligence",
      "Compte rendu écrit après chaque audience",
      "Réponse à vos demandes sous 24 heures ouvrées",
    ],
    factTitle: "Le cabinet en bref",
    facts: [
      { k: "Ordre", v: "Ordre National des Avocats de Tunisie" },
      { k: "Barreau", v: "Barreau de Tunis" },
      { k: "Juridictions", v: "Toute la République tunisienne" },
      { k: "Langues de travail", v: "Arabe · Français · Anglais · Italien" },
    ],
    langTitle: "Langues de travail",
    languages: [
      { name: "Arabe", level: "Langue maternelle", pct: 100 },
      { name: "Français", level: "Bilingue", pct: 95 },
      { name: "Anglais", level: "Professionnel", pct: 75 },
      { name: "Italien", level: "Notions", pct: 45 },
    ],
    caption: "Cabinet — Avenue Habib Bourguiba, Tunis",
    badge: { value: "12", label: "années d'exercice du droit" },
  },
  engagements: {
    title: "Trois engagements",
    titleEm: "contractuels.",
    items: [
      {
        num: "I",
        title: "Information continue",
        text: "Après chaque audience ou diligence, un compte rendu écrit : décision rendue, échéance suivante, options disponibles. Vous n'apprenez jamais un événement par hasard.",
      },
      {
        num: "II",
        title: "Confidentialité absolue",
        text: "Le secret professionnel de l'avocat est absolu et protégé par la loi. Vos pièces, échanges et coordonnées ne sont ni communiqués ni utilisés à d'autres fins.",
      },
      {
        num: "III",
        title: "Délais tenus",
        text: "Un calendrier prévisionnel est remis par écrit dès la stratégie arrêtée. Toute échéance procédurale est suivie au cabinet, avec relance automatique.",
      },
    ],
  },
  expertise: {
    eyebrow: "02 — Domaines d'intervention",
    title: "Domaines",
    titleEm: "d'intervention",
    lead: "Une pratique généraliste exigeante, adossée à une spécialisation en droit des sociétés, en recouvrement de créances et en voies d'exécution.",
    note: "Références légales indicatives — chaque dossier est analysé au regard des textes en vigueur.",
    details: "Détail de la mission",
    close: "Réduire",
    laws: "Textes de référence",
    items: [
      {
        title: "Droit des sociétés & des affaires",
        text: "Constitution, vie sociale, opérations sur titres et contentieux entre associés.",
        points: [
          "Création de SARL, SUARL et SA — statuts et formalités",
          "Approbation des comptes, cession de parts, augmentation de capital",
          "Rédaction et négociation de contrats commerciaux et de distribution",
          "Baux commerciaux, cession de fonds de commerce, litiges entre associés",
        ],
        laws: "Code des sociétés commerciales (loi n° 2000-93)",
      },
      {
        title: "Droit de la famille & statut personnel",
        text: "Accompagnement des procédures familiales avec discrétion et rigueur.",
        points: [
          "Divorce judiciaire et divorce par consentement mutuel",
          "Garde des enfants, droit de visite et pension alimentaire",
          "Répartition des biens acquis pendant le mariage",
          "Successions, partage et actes de notoriété",
        ],
        laws: "Code du statut personnel (1956)",
      },
      {
        title: "Immobilier & foncier",
        text: "Sécurisation des titres et des opérations, du compromis à l'enregistrement.",
        points: [
          "Vérification et sécurisation des titres fonciers",
          "Promesses de vente, actes, publicité foncière et enregistrement",
          "Litiges de construction, permis de bâtir et urbanisme",
          "Baux d'habitation, expulsion et exécution des décisions",
        ],
        laws: "Code des droits réels · Réglementation de l'urbanisme",
      },
      {
        title: "Droit du travail & social",
        text: "Défense des salariés et des employeurs, avec la même exigence de preuve.",
        points: [
          "Licenciement, faute grave et calcul des indemnités légales",
          "Contrats de travail, règlement intérieur et sanctions",
          "Accidents du travail, CNSS et sécurité sociale",
          "Négociation transactionnelle de fins de contrat collectives ou individuelles",
        ],
        laws: "Code du travail (loi n° 66-27)",
      },
      {
        title: "Droit pénal & pénal des affaires",
        text: "Une défense présente dès les premières heures de la procédure.",
        points: [
          "Assistance immédiate en garde à vue et enquête préliminaire",
          "Chèques sans provision, escroquerie et abus de confiance",
          "Faux et usage de faux, fraude fiscale et douanière",
          "Constitution de partie civile et action en indemnisation",
        ],
        laws: "Code pénal · Loi n° 2016-52 relative aux chèques",
      },
      {
        title: "Recouvrement & voies d'exécution",
        text: "Transformer un titre exécutoire en paiement effectivement recouvré.",
        points: [
          "Injonction de payer et procédures d'urgence",
          "Saisie-arrêt, saisie mobilière et saisie immobilière",
          "Mesures conservatoires et recherche de solvabilité du débiteur",
          "Exequatur des jugements étrangers — sociétés et Tunisiens à l'étranger",
        ],
        laws: "Code de procédure civile · Code de commerce",
      },
    ],
  },
  method: {
    eyebrow: "03 — Méthode",
    title: "Une méthode",
    titleEm: "structurée.",
    lead: "Quatre étapes, des délais annoncés et une information continue jusqu'à l'exécution de la décision.",
    steps: [
      {
        num: "01",
        title: "Entretien",
        text: "Un premier entretien confidentiel, au cabinet ou par visioconférence, pour établir les faits, les pièces disponibles et les objectifs poursuivis.",
      },
      {
        num: "02",
        title: "Étude préliminaire",
        text: "Analyse des pièces, recherche des textes applicables et de la jurisprudence récente, évaluation des risques et des délais réalistes.",
      },
      {
        num: "03",
        title: "Stratégie & convention",
        text: "Note écrite : voie retenue (négociation, médiation, action judiciaire), calendrier prévisionnel et convention d'honoraires.",
      },
      {
        num: "04",
        title: "Procédure & exécution",
        text: "Rédaction, plaidoirie, suivi des délais et exécution de la décision — avec compte rendu après chaque audience.",
      },
    ],
  },
  career: {
    eduEyebrow: "04 — Formation",
    eduTitle: "Formation",
    eduEm: "académique",
    edu: [
      {
        year: "2012",
        title: "Licence en droit privé",
        place: "Faculté des sciences juridiques, politiques et sociales de Tunis",
      },
      {
        year: "2015",
        title: "Master professionnel en droit des affaires",
        place: "Faculté de droit et des sciences politiques de Sousse",
      },
      {
        year: "2017",
        title: "Certificat d'aptitude à la profession d'avocat",
        place: "Ordre National des Avocats de Tunisie",
      },
      {
        year: "2019",
        title: "Certificat en arbitrage et médiation",
        place: "Centre de conciliation et d'arbitrage de Tunis (CCAT)",
      },
    ],
    expEyebrow: "Parcours professionnel",
    expTitle: "Expérience",
    expEm: "professionnelle",
    exp: [
      {
        period: "2017 — 2020",
        title: "Collaborateur — contentieux civil et commercial",
        place: "Cabinet d'avocats, Avenue Habib Bourguiba — Tunis",
        text: "Rédaction de mémoires et conclusions, audiences civiles et commerciales, suivi des dossiers d'exécution et assistance aux clients en phase d'expertise.",
      },
      {
        period: "2020 — 2023",
        title: "Avocat — droit des affaires et recouvrement",
        place: "Cabinet d'avocats, Les Berges du Lac — Tunis",
        text: "Gestion autonome d'un portefeuille de créances et de litiges commerciaux pour des PME tunisiennes et des filiales de groupes étrangers ; injonctions de payer et saisies-arrêts.",
      },
      {
        period: "2023 — 2025",
        title: "Responsable du département sociétés & contentieux",
        place: "Cabinet d'avocats — Tunis",
        text: "Encadrement d'une équipe de collaborateurs, audits contractuels, opérations sur titres, arbitrage commercial et suivi des contentieux devant les cours d'appel de Tunis et Sousse.",
      },
      {
        period: "2026 — Présent",
        title: "Installation du cabinet — Avenue Habib Bourguiba, Tunis",
        place: "Cabinet de Maître Brahim Majdoub",
        text: "Ouverture du cabinet principal : conseil préventif, rédaction d'actes, arbitrage et contentieux devant les juridictions de Tunis, Sousse, Sfax et Djerba.",
      },
    ],
    courtsTitle: "Juridictions et instances",
    courts: [
      "Tribunaux de première instance — Tunis, Ariana, Ben Arous, Sousse, Sfax",
      "Cours d'appel — Tunis, Sousse, Sfax",
      "Cour de cassation — Tunis",
      "Tribunal administratif · Centre de conciliation et d'arbitrage de Tunis",
    ],
  },
  testimonies: {
    eyebrow: "05 — Avis clients",
    title: "Ce que disent",
    titleEm: "les clients.",
    note: "Exemples illustratifs de retours clients, présentés à titre de gabarit : à remplacer, avant mise en ligne, par des avis recueillis avec le consentement écrit de chaque client.",
    items: [
      {
        quote:
          "Maître Majdoub a repris un dossier commercial complexe laissé en souffrance. Analyse claire, calendrier tenu, décision favorable en première instance.",
        name: "Sami B.",
        role: "Dirigeant de SARL — Tunis",
      },
      {
        quote:
          "Dans une procédure de divorce difficile, j'ai trouvé une écoute sans jugement et une défense ferme de mes droits et de ceux de mes enfants.",
        name: "Inès K.",
        role: "Cliente — droit de la famille",
      },
      {
        quote:
          "Un impayé de 320 000 dinars récupéré par saisie-arrêt en moins d'un an, avec des honoraires conformes au devis initial.",
        name: "Hatem M.",
        role: "Gérant — recouvrement de créances",
      },
      {
        quote:
          "Résidant en Italie, j'ai pu mener la vente de mon bien à Tunis à distance, avec des comptes rendus réguliers et une procuration bien encadrée.",
        name: "Giulia R.",
        role: "Cliente à l'étranger — immobilier",
      },
    ],
  },
  faq: {
    eyebrow: "06 — Questions fréquentes",
    title: "Vos",
    titleEm: "questions.",
    lead: "Honoraires, délais, juridictions, clients à l'étranger : les réponses les plus demandées avant le premier entretien.",
    items: [
      {
        q: "Comment sont fixés les honoraires ?",
        a: "Trois bases seulement : honoraire de consultation, honoraire au forfait par étape de procédure, ou honoraire fixe complété d'un honoraire de résultat. Une convention écrite est signée avant toute diligence, conformément aux usages du Barreau de Tunis.",
      },
      {
        q: "Le premier entretien est-il payant ?",
        a: "Le premier entretien (30 à 45 minutes), au cabinet, par téléphone ou en visioconférence, est soumis à un honoraire de consultation fixe annoncé à l'avance. Il débouche sur une note d'orientation écrite si la mission est retenue.",
      },
      {
        q: "Combien de temps dure une procédure ?",
        a: "Une injonction de payer peut être obtenue en quelques semaines. Une affaire au fond devant le tribunal de première instance demande généralement 12 à 24 mois, hors appel. Une estimation réaliste vous est remise par écrit dès la stratégie arrêtée.",
      },
      {
        q: "Intervenez-vous en dehors de Tunis ?",
        a: "Oui. Le cabinet plaide à Tunis, Sousse, Sfax, Nabeul, Djerba et dans le reste de la République. Pour les dossiers éloignés, un réseau de confrères limite vos déplacements et vos frais.",
      },
      {
        q: "Accompagnez-vous les Tunisiens de l'étranger ?",
        a: "Régulièrement : vente ou succession d'un bien en Tunisie, litige commercial, injonction de payer, exequatur d'un jugement étranger. Les dossiers se conduisent à distance par visioconférence, procuration légalisée et transmission sécurisée des pièces.",
      },
      {
        q: "Mes informations restent-elles confidentielles ?",
        a: "Le secret professionnel de l'avocat est absolu et protégé par la loi. Vos documents, échanges et coordonnées ne sont jamais communiqués à des tiers, y compris après la fin de la mission.",
      },
    ],
  },
  ctaBand: {
    title: "Votre dossier mérite",
    titleEm: "une réponse claire.",
    text: "Exposez-le en quelques lignes : il fait l'objet d'une étude préliminaire et d'un devis d'honoraires avant toute démarche.",
    button: "Demander un rendez-vous",
  },
  contact: {
    eyebrow: "07 — Contact",
    title: "Exposer",
    titleEm: "votre dossier.",
    lead: "Décrivez brièvement votre situation, les parties concernées et les délais éventuels. Une réponse vous est adressée sous 24 heures ouvrées.",
    cabinet: "Le cabinet",
    address: "18, Avenue Habib Bourguiba — Immeuble Le Colisée, 4ᵉ étage — Tunis 1001, Tunisie",
    phoneLabel: "Téléphone",
    emailLabel: "E-mail",
    hoursLabel: "Horaires d'ouverture",
    hours: [
      { d: "Lundi — Vendredi", h: "8h30 — 17h30" },
      { d: "Samedi", h: "9h00 — 12h00" },
      { d: "Dimanche & jours fériés", h: "Urgences uniquement" },
    ],
    followLabel: "Suivre le cabinet",
    formTitle: "Demande de rendez-vous",
    form: {
      name: "Nom & prénom",
      namePh: "Ex. Karim Ben Salah",
      phone: "Téléphone",
      phonePh: "+216 __ ___ ___",
      email: "E-mail",
      emailPh: "vous@exemple.tn",
      subject: "Nature du dossier",
      subjects: [
        "Droit des sociétés / affaires",
        "Statut personnel / famille",
        "Immobilier / foncier",
        "Droit du travail",
        "Pénal / pénal des affaires",
        "Recouvrement / exécution",
        "Autre",
      ],
      date: "Date souhaitée",
      slot: "Créneau souhaité",
      slots: ["Matin (8h30 — 12h)", "Après-midi (13h30 — 17h30)", "Par téléphone", "Visioconférence"],
      message: "Votre message",
      messagePh:
        "Exposez brièvement les faits, les parties concernées, les démarches déjà engagées et les délais éventuels…",
      submit: "Transmettre la demande",
      whatsapp: "Transmettre par WhatsApp",
      note: "Vos informations sont traitées de manière strictement confidentielle. Aucune diligence n'est engagée avant la signature d'une convention d'honoraires.",
      required: "Merci d'indiquer votre nom, un moyen de contact et un exposé succinct de votre situation.",
      greeting: "Bonjour Maître Majdoub,",
      sending: "Envoi en cours…",
      sentTitle: "Votre demande a été transmise.",
      sentSub: "Le cabinet vous répondra sous 24 heures ouvrées.",
      preparedTitle: "Votre demande est prête à être transmise.",
      preparedSub:
        "Aucun envoi automatique n'est configuré sur ce site : choisissez votre canal ci-dessous, votre message est déjà rédigé.",
      networkError:
        "L'envoi a échoué. Vérifiez votre connexion puis réessayez, ou utilisez l'un des canaux ci-dessous.",
      channelLabel: "Choisir un canal d'envoi",
      reopen: "Transmettre une autre demande",
      summaryTitle: "Récapitulatif de la demande",
    },
  },
  footer: {
    tagline:
      "Cabinet d'avocat inscrit au Barreau de Tunis — conseil, négociation et plaidoirie devant les juridictions tunisiennes.",
    navTitle: "Navigation",
    expertiseTitle: "Domaines",
    legalTitle: "Informations",
    legal1: "Les informations publiées sur ce site sont générales et ne constituent pas une consultation juridique.",
    legal2:
      "Coordonnées de démonstration — à remplacer par les informations officielles du cabinet (Ordre National des Avocats de Tunisie).",
    legal3:
      "Chiffres et témoignages présentés à titre indicatif dans cette version ; ils seront étayés par les pièces du cabinet avant toute diffusion publique.",
    rights: "Tous droits réservés.",
    top: "Haut de page",
  },
  legal: {
    title: "Mentions légales & confidentialité",
    editor: "Éditeur du site",
    editorValue: "Cabinet de Maître Brahim Majdoub, avocat inscrit au Barreau de Tunis.",
    hosting: "Hébergement",
    hostingValue: "À préciser lors de la mise en production.",
    dataTitle: "Données personnelles",
    dataBody:
      "Les informations saisies dans le formulaire servent uniquement à préparer votre demande : elles ne sont ni enregistrées par ce site, ni communiquées à des tiers. Conformément à la loi organique n° 2004-63 relative à la protection des données personnelles, vous disposez d'un droit d'accès, de rectification et de suppression, à exercer auprès du cabinet par l'un des canaux de contact ci-dessus.",
    cookiesTitle: "Cookies",
    cookies:
      "Ce site ne dépose aucun cookie de mesure d'audience. La carte intégrée est servie par Google Maps, susceptible d'appliquer ses propres règles de confidentialité.",
  },
};

const en: typeof fr = {
  seo: {
    title: "Maître Brahim Majdoub — Lawyer at the Tunis Bar",
    description:
      "Office of Maître Brahim Majdoub, lawyer enrolled at the Tunis Bar (Tunisia). Company law, personal status, real estate, employment, business criminal law, debt recovery and enforcement. Preventive advice, negotiation and advocacy — fees agreed in writing.",
  },
  brand: {
    name: "Brahim Majdoub",
    initials: "BM",
  },
  a11y: {
    skip: "Skip to main content",
    menu: "Open the menu",
    close: "Close the menu",
    lang: "Choose the site language",
    map: "Firm location on Google Maps",
    facebook: "Firm Facebook page",
    whatsapp: "Contact the firm on WhatsApp",
    email: "Email the firm",
    phone: "Call the firm",
    top: "Back to the top of the page",
    nav: "Main navigation",
  },
  nav: {
    about: "The firm",
    expertise: "Practice",
    method: "Method",
    career: "Career",
    testimonies: "Reviews",
    faq: "FAQ",
    contact: "Contact",
    book: "Request an appointment",
    call: "Call",
  },
  utility: "National Bar Association of Tunisia — Tunis Bar",
  hero: {
    eyebrow: "Attorney at the Tunis Bar — Tunisia",
    titleTop: "The art of",
    titleEm: "Defence",
    lead: "Registered with the Tunis Bar, I advise individuals, companies and investors before the Tunisian courts: preventive advice, negotiation and advocacy — fees agreed in writing, continuous reporting.",
    ctaPrimary: "Request an appointment",
    ctaSecondary: "About the firm",
    portraitCaption: "Maître Brahim Majdoub",
    portraitRole: "Attorney at the Tunis Bar",
    credentials: [
      { k: "Bar", v: "Tunis — ONAT" },
      { k: "Courts", v: "Tunis · Sousse · Sfax · Djerba" },
      { k: "Languages", v: "Arabic · French · English" },
    ],
  },
  stats: {
    eyebrow: "The firm in figures",
    items: [
      { value: 12, suffix: "+", label: "years in practice" },
      { value: 850, suffix: "+", label: "files handled" },
      { value: 6, suffix: "", label: "practice areas" },
      { value: 24, suffix: "h", label: "response time" },
    ],
  },
  about: {
    eyebrow: "01 — The firm",
    title: "A litigator and adviser with a",
    titleEm: "written method.",
    lead: "A demanding method: written preliminary review, fees agreed in advance, written report after every hearing.",
    p1: "Registered with the National Bar Association of Tunisia, I advise and defend individuals, companies and investors. My background in private and business law shaped a practice built on procedural mastery, precise drafting and respect for announced deadlines.",
    p2: "I appear before courts of first instance, courts of appeal and the Court of Cassation, as well as in criminal matters and before arbitration bodies. Every file is covered by a written agreement setting out the mission, the provisional calendar and the fee — with no commitment of any kind before your approval.",
    bullets: [
      "Written preliminary review of every file",
      "Fee agreement signed before any step is taken",
      "Written report after each hearing",
      "All requests answered within 24 working hours",
    ],
    factTitle: "The firm at a glance",
    facts: [
      { k: "Association", v: "National Bar Association of Tunisia" },
      { k: "Bar", v: "Tunis Bar" },
      { k: "Courts", v: "Throughout the Republic of Tunisia" },
      { k: "Working languages", v: "Arabic · French · English · Italian" },
    ],
    langTitle: "Working languages",
    languages: [
      { name: "Arabic", level: "Native", pct: 100 },
      { name: "French", level: "Bilingual", pct: 95 },
      { name: "English", level: "Professional", pct: 75 },
      { name: "Italian", level: "Basic", pct: 45 },
    ],
    caption: "The firm — Avenue Habib Bourguiba, Tunis",
    badge: { value: "12", label: "years in the practice of law" },
  },
  engagements: {
    title: "Three contractual",
    titleEm: "commitments.",
    items: [
      {
        num: "I",
        title: "Continuous reporting",
        text: "A written report after each hearing or step: decision issued, next deadline, available options. You never learn of an event by chance.",
      },
      {
        num: "II",
        title: "Absolute confidentiality",
        text: "An attorney's professional privilege is absolute and protected by law. Your documents, exchanges and contact details are never shared or used for other purposes.",
      },
      {
        num: "III",
        title: "Deadlines kept",
        text: "A provisional calendar is provided in writing as soon as the strategy is set. Every procedural deadline is tracked at the firm, with automatic reminders.",
      },
    ],
  },
  expertise: {
    eyebrow: "02 — Practice areas",
    title: "Practice",
    titleEm: "areas",
    lead: "A demanding general practice, backed by specialisation in company law, debt recovery and enforcement proceedings.",
    note: "Legal references are indicative — every file is analysed under the legislation in force.",
    details: "Scope of work",
    close: "Collapse",
    laws: "Key legislation",
    items: [
      {
        title: "Company & business law",
        text: "Incorporation, corporate life, transactions and shareholder disputes.",
        points: [
          "Incorporation of SARL, SUARL and SA — articles and formalities",
          "Approval of accounts, transfer of shares, capital increases",
          "Drafting and negotiating commercial and distribution contracts",
          "Commercial leases, sale of business assets, shareholder litigation",
        ],
        laws: "Commercial Companies Code (Law No. 2000-93)",
      },
      {
        title: "Family law & personal status",
        text: "Support through family proceedings with discretion and rigour.",
        points: [
          "Judicial divorce and divorce by mutual consent",
          "Child custody, visitation rights and maintenance",
          "Division of assets acquired during marriage",
          "Successions, estate division and certificates of inheritance",
        ],
        laws: "Personal Status Code (1956)",
      },
      {
        title: "Real estate & property",
        text: "Securing titles and transactions, from the preliminary agreement to registration.",
        points: [
          "Verification and protection of land titles",
          "Preliminary sale agreements, deeds and land registration",
          "Construction disputes, building permits and planning rules",
          "Residential leases, eviction and enforcement of decisions",
        ],
        laws: "Real Rights Code · Urban planning regulations",
      },
      {
        title: "Employment & social law",
        text: "Defending employees and employers with the same standard of evidence.",
        points: [
          "Dismissal, gross misconduct and statutory compensation",
          "Employment contracts, internal rules and disciplinary sanctions",
          "Work accidents, CNSS and social security",
          "Collective or individual negotiated termination agreements",
        ],
        laws: "Labour Code (Law No. 66-27)",
      },
      {
        title: "Criminal & white-collar crime",
        text: "A defence present from the first hours of proceedings.",
        points: [
          "Immediate assistance during police custody and preliminary inquiry",
          "Bounced cheques, fraud and breach of trust",
          "Forgery, tax and customs fraud",
          "Filing as a civil party and claiming compensation",
        ],
        laws: "Penal Code · Law No. 2016-52 on cheques",
      },
      {
        title: "Debt recovery & enforcement",
        text: "Turning an enforceable title into money actually recovered.",
        points: [
          "Order for payment and urgent procedures",
          "Attachment of debts, movable and immovable property",
          "Protective measures and debtor solvency investigations",
          "Recognition of foreign judgments — companies and Tunisians abroad",
        ],
        laws: "Code of Civil Procedure · Commercial Code",
      },
    ],
  },
  method: {
    eyebrow: "03 — Method",
    title: "A structured",
    titleEm: "method.",
    lead: "Four steps, stated deadlines and continuous reporting through to enforcement of the decision.",
    steps: [
      {
        num: "01",
        title: "Consultation",
        text: "A confidential first meeting, at the office or by video call, to establish the facts, the available evidence and your objectives.",
      },
      {
        num: "02",
        title: "Preliminary review",
        text: "Review of documents, research of applicable statutes and recent case law, assessment of risks and realistic timeframes.",
      },
      {
        num: "03",
        title: "Strategy & agreement",
        text: "A written note: route selected (negotiation, mediation, court action), provisional calendar and fee agreement.",
      },
      {
        num: "04",
        title: "Proceedings & enforcement",
        text: "Drafting, pleading, deadline monitoring and enforcement of the decision — with a report after every hearing.",
      },
    ],
  },
  career: {
    eduEyebrow: "04 — Education",
    eduTitle: "Academic",
    eduEm: "background",
    edu: [
      {
        year: "2012",
        title: "Bachelor of Laws (private law)",
        place: "Faculty of Legal, Political and Social Sciences of Tunis",
      },
      {
        year: "2015",
        title: "Professional Master in business law",
        place: "Faculty of Law and Political Sciences of Sousse",
      },
      {
        year: "2017",
        title: "Certificate of aptitude for the legal profession",
        place: "National Bar Association of Tunisia",
      },
      {
        year: "2019",
        title: "Certificate in arbitration and mediation",
        place: "Tunis Conciliation and Arbitration Centre (CCAT)",
      },
    ],
    expEyebrow: "Professional track record",
    expTitle: "Professional",
    expEm: "experience",
    exp: [
      {
        period: "2017 — 2020",
        title: "Associate — civil and commercial litigation",
        place: "Law firm, Avenue Habib Bourguiba — Tunis",
        text: "Drafting submissions and pleadings, civil and commercial hearings, monitoring enforcement files and assisting clients during expert proceedings.",
      },
      {
        period: "2020 — 2023",
        title: "Attorney — business law and debt recovery",
        place: "Law firm, Les Berges du Lac — Tunis",
        text: "Independent management of a portfolio of receivables and commercial disputes for Tunisian SMEs and subsidiaries of foreign groups; orders for payment and attachments of debts.",
      },
      {
        period: "2023 — 2025",
        title: "Head of the corporate & litigation department",
        place: "Law firm — Tunis",
        text: "Supervising a team of associates, contract audits, share transactions, commercial arbitration and litigation before the Tunis and Sousse courts of appeal.",
      },
      {
        period: "2026 — Present",
        title: "Establishing the firm — Avenue Habib Bourguiba, Tunis",
        place: "Law office of Maître Brahim Majdoub",
        text: "Opening the main office: preventive advice, drafting, arbitration and litigation before the courts of Tunis, Sousse, Sfax and Djerba.",
      },
    ],
    courtsTitle: "Courts and bodies",
    courts: [
      "Courts of first instance — Tunis, Ariana, Ben Arous, Sousse, Sfax",
      "Courts of appeal — Tunis, Sousse, Sfax",
      "Court of Cassation — Tunis",
      "Administrative Court · Tunis Conciliation and Arbitration Centre",
    ],
  },
  testimonies: {
    eyebrow: "05 — Client reviews",
    title: "What clients",
    titleEm: "say.",
    note: "Illustrative examples of client feedback, shown as a template: to be replaced, before going live, with reviews collected with each client's written consent.",
    items: [
      {
        quote:
          "Maître Majdoub took over a complex commercial file that had been left pending. Clear analysis, deadlines kept, a favourable first-instance decision.",
        name: "Sami B.",
        role: "SARL director — Tunis",
      },
      {
        quote:
          "In a difficult divorce, I found judgement-free listening and a firm defence of my rights and those of my children.",
        name: "Inès K.",
        role: "Client — family law",
      },
      {
        quote:
          "MAD 320,000 recovered through attachment of debts in under a year, with fees exactly as quoted in the initial estimate.",
        name: "Hatem M.",
        role: "Manager — debt recovery",
      },
      {
        quote:
          "Living in Italy, I handled the sale of my property in Tunis remotely, with regular reports and a properly structured power of attorney.",
        name: "Giulia R.",
        role: "Client abroad — real estate",
      },
    ],
  },
  faq: {
    eyebrow: "06 — Frequently asked questions",
    title: "Your",
    titleEm: "questions.",
    lead: "Fees, timeframes, courts, clients abroad: the answers most requested before the first consultation.",
    items: [
      {
        q: "How are fees set?",
        a: "Three bases only: consultation fee, fixed fee per procedural stage, or a fixed fee plus a success fee. A written agreement is signed before any step is taken, in line with the practice of the Tunis Bar.",
      },
      {
        q: "Is the first consultation chargeable?",
        a: "The first consultation (30 to 45 minutes), at the office, by phone or by video call, is subject to a fixed consultation fee announced in advance. It leads to a written guidance note if the engagement is agreed.",
      },
      {
        q: "How long do proceedings take?",
        a: "An order for payment can be obtained within weeks. A case on the merits before the court of first instance generally takes 12 to 24 months, excluding appeal. A realistic estimate is provided in writing as soon as the strategy is set.",
      },
      {
        q: "Do you work outside Tunis?",
        a: "Yes. The firm pleads in Tunis, Sousse, Sfax, Nabeul, Djerba and across the Republic. For distant files, a network of colleagues limits your travel and costs.",
      },
      {
        q: "Do you assist Tunisians living abroad?",
        a: "Regularly: sale or inheritance of property in Tunisia, commercial disputes, orders for payment, recognition of foreign judgments. Files are handled remotely through video calls, legalised powers of attorney and secure transfer of documents.",
      },
      {
        q: "Is my information confidential?",
        a: "An attorney's professional privilege is absolute and protected by law. Your documents, exchanges and contact details are never shared with third parties, including after the engagement ends.",
      },
    ],
  },
  ctaBand: {
    title: "Your file deserves",
    titleEm: "a clear answer.",
    text: "Set it out in a few lines: it receives a preliminary review and a fee estimate before any step is taken.",
    button: "Request an appointment",
  },
  contact: {
    eyebrow: "07 — Contact",
    title: "Set out",
    titleEm: "your file.",
    lead: "Briefly describe your situation, the parties involved and any deadlines. You will receive an answer within 24 working hours.",
    cabinet: "The office",
    address: "18, Avenue Habib Bourguiba — Immeuble Le Colisée, 4th floor — Tunis 1001, Tunisia",
    phoneLabel: "Phone",
    emailLabel: "E-mail",
    hoursLabel: "Opening hours",
    hours: [
      { d: "Monday — Friday", h: "8:30 — 17:30" },
      { d: "Saturday", h: "9:00 — 12:00" },
      { d: "Sunday & public holidays", h: "Urgent matters only" },
    ],
    followLabel: "Follow the firm",
    formTitle: "Appointment request",
    form: {
      name: "Full name",
      namePh: "e.g. Karim Ben Salah",
      phone: "Phone",
      phonePh: "+216 __ ___ ___",
      email: "E-mail",
      emailPh: "you@example.tn",
      subject: "Type of matter",
      subjects: [
        "Company / business law",
        "Personal status / family",
        "Real estate / property",
        "Employment law",
        "Criminal / business crime",
        "Debt recovery / enforcement",
        "Other",
      ],
      date: "Preferred date",
      slot: "Preferred slot",
      slots: ["Morning (8:30 — 12:00)", "Afternoon (13:30 — 17:30)", "By phone", "Video call"],
      message: "Your message",
      messagePh: "Briefly set out the facts, the parties involved, any steps already taken and applicable deadlines…",
      submit: "Send request",
      whatsapp: "Send via WhatsApp",
      note: "Your information is treated as strictly confidential. No step is taken before a fee agreement is signed.",
      required: "Please provide your name, a way to contact you and a short description of your situation.",
      greeting: "Dear Maître Majdoub,",
      sending: "Sending…",
      sentTitle: "Your request has been sent.",
      sentSub: "The firm will reply within 24 working hours.",
      preparedTitle: "Your request is ready to send.",
      preparedSub:
        "No automatic sending is configured on this site: pick a channel below — your message is already drafted.",
      networkError: "Sending failed. Check your connection and try again, or use one of the channels below.",
      channelLabel: "Choose a sending channel",
      reopen: "Send another request",
      summaryTitle: "Request summary",
    },
  },
  footer: {
    tagline: "Law firm registered with the Tunis Bar — advice, negotiation and advocacy before the Tunisian courts.",
    navTitle: "Navigation",
    expertiseTitle: "Practice areas",
    legalTitle: "Information",
    legal1: "Information published on this site is general and does not constitute legal advice.",
    legal2:
      "Demo contact details — to be replaced with the firm's official information (National Bar Association of Tunisia).",
    legal3:
      "Figures and testimonials shown here are indicative for this version; they will be substantiated by the firm's records before any public release.",
    rights: "All rights reserved.",
    top: "Back to top",
  },
  legal: {
    title: "Legal notice & privacy",
    editor: "Site publisher",
    editorValue: "Office of Maître Brahim Majdoub, lawyer registered with the Tunis Bar.",
    hosting: "Hosting",
    hostingValue: "To be specified before going live.",
    dataTitle: "Personal data",
    dataBody:
      "The information entered in the form is used solely to prepare your request: it is neither stored by this site nor passed on to third parties. In line with Organic Law No. 2004-63 on the protection of personal data, you may exercise your rights of access, rectification and erasure by contacting the firm through any of the channels above.",
    cookiesTitle: "Cookies",
    cookies:
      "This site sets no analytics cookies. The embedded map is served by Google Maps, which may apply its own privacy rules.",
  },
};

const ar: typeof fr = {
  seo: {
    title: "الأستاذ إبراهيم مجدوب — محام بعمادة محامي تونس",
    description:
      "مكتب الأستاذ إبراهيم مجدوب، المحامي المسجّل بالعمادة الوطنية للمحامين بتونس: قانون الشركات، الأحوال الشخصية، العقار، قانون الشغل، الجزائي الاقتصادي، استخلاص الديون والتنفيذ — استشارة وتفاوض ومرافعة بأتعاب متفق عليها كتابة.",
  },
  brand: {
    name: "إبراهيم مجدوب",
    initials: "إ م",
  },
  a11y: {
    skip: "الانتقال إلى المحتوى الرئيسي",
    menu: "فتح القائمة",
    close: "إغلاق القائمة",
    lang: "اختيار لغة الموقع",
    map: "موقع المكتب على خرائط جوجل",
    facebook: "صفحة المكتب على فيسبوك",
    whatsapp: "مراسلة المكتب على واتساب",
    email: "مراسلة المكتب بالبريد الإلكتروني",
    phone: "الاتصال الهاتفي بالمكتب",
    top: "العودة إلى أعلى الصفحة",
    nav: "التنقل الرئيسي",
  },
  nav: {
    about: "المكتب",
    expertise: "مجالات التدخل",
    method: "المنهجية",
    career: "المسار",
    testimonies: "آراء",
    faq: "أسئلة",
    contact: "اتصال",
    book: "طلب موعد",
    call: "اتصل",
  },
  utility: "الهيئة الوطنية للمحامين بتونس — عمادة محامي تونس",
  hero: {
    eyebrow: "محام بالعمادة الوطنية للمحامين بتونس",
    titleTop: "فن",
    titleEm: "الدفاع",
    lead: "محام مسجّل بالعمادة الوطنية للمحامين بتونس، أواكب الأفراد والشركات والمستثمرين أمام المحاكم التونسية: استشارة وقائية، تفاوض ومرافعة — بأتعاب متفق عليها كتابة وإخبار متواصل.",
    ctaPrimary: "طلب موعد",
    ctaSecondary: "تعريف بالمكتب",
    portraitCaption: "الأستاذ إبراهيم مجدوب",
    portraitRole: "محام بالعمادة الوطنية للمحامين بتونس",
    credentials: [
      { k: "العمادة", v: "تونس — الهيئة الوطنية" },
      { k: "المحاكم", v: "تونس · سوسة · صفاقس · جربة" },
      { k: "اللغات", v: "العربية · الفرنسية · الإنجليزية" },
    ],
  },
  stats: {
    eyebrow: "المكتب بالأرقام",
    items: [
      { value: 12, suffix: "+", label: "سنة من الممارسة" },
      { value: 850, suffix: "+", label: "ملف تمّت متابعته" },
      { value: 6, suffix: "", label: "مجالات تدخل" },
      { value: 24, suffix: "س", label: "مدة الرد" },
    ],
  },
  about: {
    eyebrow: "١ — المكتب",
    title: "محام نزاعات واستشارات",
    titleEm: "بمنهجية مكتوبة.",
    lead: "منهجية صارمة: دراسة أولية مكتوبة، أتعاب محدّدة مسبقًا، وتقرير كتابي بعد كل جلسة.",
    p1: "مسجّل بجدول الهيئة الوطنية للمحامين بتونس، أقدّم الاستشارة والدفاع للأفراد والشركات والمستثمرين. مساري في القانون الخاص وقانون الأعمال أرسى ممارسة تقوم على إتقان الإجراءات ودقة الصياغة والالتزام بالآجال المعلنة.",
    p2: "أترافع أمام المحاكم الابتدائية ومحاكم الاستئناف ومحكمة التعقيب، وفي المادة الجزائية، وأمام هيئات التحكيم. كل ملف يخضع لاتفاق مكتوب يحدّد المهمة والجدول الزمني التقديري والأتعاب — دون أي التزام من طرفكم قبل الموافقة.",
    bullets: [
      "دراسة أولية مكتوبة لكل ملف",
      "اتفاق أتعاب يُوقَّع قبل أي إجراء",
      "تقرير مكتوب بعد كل جلسة",
      "الرد على طلباتكم داخل 24 ساعة عمل",
    ],
    factTitle: "المكتب في سطور",
    facts: [
      { k: "الهيئة", v: "الهيئة الوطنية للمحامين بتونس" },
      { k: "العمادة", v: "عمادة محامي تونس" },
      { k: "المحاكم", v: "كامل الجمهورية التونسية" },
      { k: "لغات العمل", v: "العربية · الفرنسية · الإنجليزية · الإيطالية" },
    ],
    langTitle: "لغات العمل",
    languages: [
      { name: "العربية", level: "اللغة الأم", pct: 100 },
      { name: "الفرنسية", level: "ثنائي اللغة", pct: 95 },
      { name: "الإنجليزية", level: "مهني", pct: 75 },
      { name: "الإيطالية", level: "مبادئ", pct: 45 },
    ],
    caption: "المكتب — شارع الحبيب بورقيبة، تونس",
    badge: { value: "12", label: "سنة في ممارسة القانون" },
  },
  engagements: {
    title: "ثلاثة التزامات",
    titleEm: "تعاقدية.",
    items: [
      {
        num: "I",
        title: "إخبار متواصل",
        text: "تقرير كتابي بعد كل جلسة أو إجراء: القرار الصادر، الأجل الموالي، الخيارات المتاحة. لا تعلمون بأي مستجد بالمصادفة.",
      },
      {
        num: "II",
        title: "سرية مطلقة",
        text: "السر المهني للمحامي مطلق ويحميه القانون. وثائقكم ومراسلاتكم ومعطياتكم لا تُنقل ولا تُستعمل لأي غرض آخر.",
      },
      {
        num: "III",
        title: "احترام الآجال",
        text: "يُسلَّم جدول زمني تقديري كتابةً فور إقرار الاستراتيجية، وتُتابَع كل أجَلة إجرائية داخل المكتب مع تذكير تلقائي.",
      },
    ],
  },
  expertise: {
    eyebrow: "٢ — مجالات التدخل",
    title: "مجالات",
    titleEm: "التدخل",
    lead: "ممارسة عامة صارمة، مدعومة بتخصص في قانون الشركات واستخلاص الديون وطرق التنفيذ.",
    note: "المراجع القانونية إرشادية — ويُدرَس كل ملف وفق النصوص الجاري بها العمل.",
    details: "تفاصيل المهمة",
    close: "إغلاق",
    laws: "النصوص المرجعية",
    items: [
      {
        title: "قانون الشركات والأعمال",
        text: "التأسيس، الحياة الاجتماعية، العمليات على الأسهم والنزاعات بين الشركاء.",
        points: [
          "تأسيس الشركات ذات المسؤولية المحدودة والشركات ذات الشخص الواحد والشركات المساهمة",
          "المصادقة على القوائم المالية، التفريط في الأسهم، الترفيع في رأس المال",
          "صياغة وتفاوض العقود التجارية والتوزيع",
          "الكراء التجاري والتفويت في الأصل التجاري ونزاعات الشركاء",
        ],
        laws: "مجلة الشركات التجارية (قانون عدد 93 لسنة 2000)",
      },
      {
        title: "قانون الأسرة والأحوال الشخصية",
        text: "مواكبة القضايا الأسرية بتحفّظ ودقة.",
        points: [
          "الطلاق القضائي والطلاق بالتراضي",
          "الحضانة وحق الزيارة والنفقة",
          "تقسيم الأموال المكتسبة خلال الزواج",
          "التوريث وقسمة التركات ورسم الإراثة",
        ],
        laws: "مجلة الأحوال الشخصية (1956)",
      },
      {
        title: "العقار والملكية العقارية",
        text: "تأمين الرسوم العقارية والمعاملات من الوعد بالبيع إلى التسجيل.",
        points: [
          "التحقق من الرسوم العقارية وتأمينها",
          "وعود البيع والعمود والترسيم العقاري والتسجيل",
          "نزاعات البناء ورخص البناء والتهيئة العمرانية",
          "كراء السكن والطرد وتنفيذ الأحكام",
        ],
        laws: "مجلة الحقوق العينية · قوانين التهيئة العمرانية",
      },
      {
        title: "قانون الشغل والشؤون الاجتماعية",
        text: "الدفاع عن العملة والمؤجرين بنفس معيار الإثبات.",
        points: [
          "الطرد والخطأ الجسيم وحساب التعويضات القانونية",
          "عقود الشغل والنظام الداخلي والعقوبات التأديبية",
          "حوادث الشغل والصندوق الوطني للضمان الاجتماعي",
          "التفاوض الصلحي على إنهاء العلاقة الشغلية جماعياً أو فردياً",
        ],
        laws: "مجلة الشغل (قانون عدد 27 لسنة 1966)",
      },
      {
        title: "القانون الجزائي والجرائم الاقتصادية",
        text: "دفاع حاضر منذ الساعات الأولى للإجراءات.",
        points: [
          "المواكبة الفورية لدى الحرس النظري والبحث الابتدائي",
          "الشيكات بدون رصيد والنصب وخيانة الأمانة",
          "التزوير واستعمال المزوّر والتهرب الجبائي والديواني",
          "التقاضي بالحق الشخصي والمطالبة بالتعويض",
        ],
        laws: "المجلة الجزائية · القانون عدد 52 لسنة 2016 بشأن الشيكات",
      },
      {
        title: "استخلاص الديون وطرق التنفيذ",
        text: "تحويل السند التنفيذي إلى مبلغ مُستخلص فعلاً.",
        points: [
          "الأمر بالدفع والإجراءات الاستعجالية",
          "التمسك بالغرمية والحجز المنقول والحجز العقاري",
          "التحفظات والبحث في ملاءة المدين",
          "تفعيل الأحكام الأجنبية — الشركات والتونسيون بالخارج",
        ],
        laws: "مجلة مرافعات مدنية · المجلة التجارية",
      },
    ],
  },
  method: {
    eyebrow: "٣ — المنهجية",
    title: "منهجية",
    titleEm: "منظّمة.",
    lead: "أربع مراحل، آجال معلَنة، وإخبار متواصل إلى حين تنفيذ القرار.",
    steps: [
      {
        num: "01",
        title: "اللقاء الأول",
        text: "لقاء أول سري، بالمكتب أو بالمناظرة المرئية، لتحديد الوقائع والوثائق المتاحة والأهداف المرسومة.",
      },
      {
        num: "02",
        title: "الدراسة الأولية",
        text: "تحليل الوثائق والبحث في النصوص المطبقة وأحدث الاجتهادات، وتقييم المخاطر والآجال الواقعية.",
      },
      {
        num: "03",
        title: "الاستراتيجية والاتفاق",
        text: "مذكرة كتابية: المسار المعتمد (تفاوض، وساطة، دعوى قضائية)، الجدول الزمني التقديري واتفاق الأتعاب.",
      },
      {
        num: "04",
        title: "المرافعة والتنفيذ",
        text: "الصياغة والمرافعة ومتابعة الآجال وتنفيذ القرار — مع تقرير بعد كل جلسة.",
      },
    ],
  },
  career: {
    eduEyebrow: "٤ — التكوين",
    eduTitle: "التكوين",
    eduEm: "الأكاديمي",
    edu: [
      {
        year: "2012",
        title: "الإجازة في القانون الخاص",
        place: "كلية العلوم القانونية والسياسية والاجتماعية بتونس",
      },
      {
        year: "2015",
        title: "شهادة الماجستير المهني في قانون الأعمال",
        place: "كلية الحقوق والعلوم السياسية بسوسة",
      },
      {
        year: "2017",
        title: "شهادة الكفاءة لممارسة مهنة المحاماة",
        place: "الهيئة الوطنية للمحامين بتونس",
      },
      {
        year: "2019",
        title: "شهادة في التحكيم والوساطة",
        place: "مركز التوفيق والتحكيم بتونس",
      },
    ],
    expEyebrow: "المسار المهني",
    expTitle: "التجربة",
    expEm: "المهنية",
    exp: [
      {
        period: "2017 — 2020",
        title: "متعاون — النزاعات المدنية والتجارية",
        place: "مكتب محاماة، شارع الحبيب بورقيبة — تونس",
        text: "صياغة المذكرات والعرائض، حضور الجلسات المدنية والتجارية، متابعة ملفات التنفيذ ومواكبة الحرفاء في مرحلة الخبرة.",
      },
      {
        period: "2020 — 2023",
        title: "محام — قانون الأعمال واستخلاص الديون",
        place: "مكتب محاماة، ضفاف البحيرة — تونس",
        text: "تدبير مستقل لمحفظة ديون ونزاعات تجارية لفائدة مؤسسات صغرى ومتوسطة وشركات تابعة لمجموعات أجنبية؛ أوامر بالدفع والتمسك بالغرمية.",
      },
      {
        period: "2023 — 2025",
        title: "مسؤول قسم الشركات والنزاعات",
        place: "مكتب محاماة — تونس",
        text: "تأطير فريق من المتعاونين، مراجعة العقود، العمليات على الأسهم، التحكيم التجاري ومتابعة النزاعات أمام محكمتي استئناف تونس وسوسة.",
      },
      {
        period: "2026 — الآن",
        title: "تأسيس المكتب — شارع الحبيب بورقيبة، تونس",
        place: "مكتب الأستاذ إبراهيم مجدوب",
        text: "افتتاح المكتب الرئيسي: الاستشارة الوقائية، صياغة العقود، التحكيم والنزاعات أمام محاكم تونس وسوسة وصفاقس وجربة.",
      },
    ],
    courtsTitle: "المحاكم والهيئات",
    courts: [
      "المحاكم الابتدائية — تونس، أريانة، بن عروس، سوسة، صفاقس",
      "محاكم الاستئناف — تونس، سوسة، صفاقس",
      "محكمة التعقيب — تونس",
      "المحكمة الإدارية · مركز التوفيق والتحكيم بتونس",
    ],
  },
  testimonies: {
    eyebrow: "٥ — آراء الحرفاء",
    title: "ماذا يقول",
    titleEm: "الحرفاء.",
    note: "أمثلة توضيحية لآراء موكلين، تُعرض على سبيل النموذج: تُستبدل قبل النشر بآراء مُجمعة بموافقة كتابية من كل موكّل.",
    items: [
      {
        quote:
          "تولّى الأستاذ مجدوب ملفاً تجارياً معقداً كان معلّقاً. تحليل واضح، آجال محترمة، وحكم لصالحنا في الدرجة الأولى.",
        name: "سامي ب.",
        role: "مسيّر شركة ذات مسؤولية محدودة — تونس",
      },
      {
        quote: "في قضية طلاق صعبة وجدت إنصاتاً بلا أحكام مسبقة ودفاعاً حازماً عن حقوقي وحقوق أطفالي.",
        name: "إيناس ك.",
        role: "حريفة — قانون الأسرة",
      },
      {
        quote:
          "تمّ استخلاص دين بقيمة 320.000 دينار بواسطة التمسك بالغرمية في أقل من سنة، وبأتعاب مطابقة للتقدير الأولي.",
        name: "حاتم م.",
        role: "مسيّر — استخلاص الديون",
      },
      {
        quote: "أقيم في إيطاليا وأنجزت بيع عقاري بتونس عن بُعد، مع تقارير منتظمة وتوكيل مُحكَم الصياغة.",
        name: "جوليا ر.",
        role: "حريفة بالخارج — العقار",
      },
    ],
  },
  faq: {
    eyebrow: "٦ — أسئلة متكررة",
    title: "أسئلتكم",
    titleEm: "المتكررة.",
    lead: "الأتعاب، الآجال، المحاكم، الحرفاء بالخارج: أكثر الأسئلة تكراراً قبل اللقاء الأول.",
    items: [
      {
        q: "كيف تُحدَّد الأتعاب؟",
        a: "ثلاث قواعد فقط: أتعاب استشارة، أتعاب جزافية لكل مرحلة من الإجراءات، أو أتعاب قارة يضاف إليها أتعاب نتيجة. ويُوقَّع اتفاق كتابي قبل أي إجراء طبقاً لأعراف عمادة محامي تونس.",
      },
      {
        q: "هل اللقاء الأول مؤدى عنه؟",
        a: "اللقاء الأول (من 30 إلى 45 دقيقة) بالمكتب أو هاتفياً أو بالمناظرة المرئية مقابل أتعاب استشارة قارة تُعلن مسبقاً، وينتهي بمذكرة توجيه كتابية إذا تمّ إسناد المهمة.",
      },
      {
        q: "كم تستغرق الإجراءات؟",
        a: "يمكن الحصول على الأمر بالدفع في أسابيع. أما القضية الموضوعية أمام المحكمة الابتدائية فتستغرق عادة من 12 إلى 24 شهراً دون احتساب الاستئناف. ويُسلَّم تقدير واقعي كتابةً فور إقرار الاستراتيجية.",
      },
      {
        q: "هل تتدخلون خارج تونس العاصمة؟",
        a: "نعم. يترافع المكتب بتونس وسوسة وصفاقس ونابل وجربة وكامل الجمهورية، وبالنسبة للملفات البعيدة تحدّ شبكة من الزملاء من تنقّلاتكم ومصاريفكم.",
      },
      {
        q: "هل تواكبون التونسيين بالخارج؟",
        a: "بشكل منتظم: بيع عقار أو تركة بتونس، نزاع تجاري، أمر بالدفع، تفعيل حكم أجنبي. وتُدار الملفات عن بُعد عبر المناظرة المرئية والتوكيل المُصادق عليه وإرسال الوثائق بطريقة مؤمَّنة.",
      },
      {
        q: "هل تبقى معطياتي سرية؟",
        a: "السر المهني للمحامي مطلق ويحميه القانون. لا تُنقل وثائقكم ومراسلاتكم ومعطياتكم إلى أي طرف ثالث، حتى بعد انتهاء المهمة.",
      },
    ],
  },
  ctaBand: {
    title: "ملفكم يستحق",
    titleEm: "جواباً واضحاً.",
    text: "اعرضوه في بضعة أسطر: يخضع لدراسة أولية وتقدير للأتعاب قبل أي إجراء.",
    button: "طلب موعد",
  },
  contact: {
    eyebrow: "٧ — الاتصال",
    title: "اعرضوا",
    titleEm: "ملفكم.",
    lead: "صفوا بإيجاز وضعيتكم والأطراف المعنية والآجال المحتملة. سيصلكم الرد داخل 24 ساعة عمل.",
    cabinet: "المكتب",
    address: "18، شارع الحبيب بورقيبة — عمارة الكوليزي، الطابق الرابع — تونس 1001، تونس",
    phoneLabel: "الهاتف",
    emailLabel: "البريد الإلكتروني",
    hoursLabel: "أوقات العمل",
    hours: [
      { d: "الاثنين — الجمعة", h: "8:30 — 17:30" },
      { d: "السبت", h: "9:00 — 12:00" },
      { d: "الأحد والأعياد", h: "الحالات المستعجلة فقط" },
    ],
    followLabel: "تابعوا المكتب",
    formTitle: "طلب موعد",
    form: {
      name: "الاسم واللقب",
      namePh: "مثال: كريم بن صالح",
      phone: "الهاتف",
      phonePh: "+216 __ ___ ___",
      email: "البريد الإلكتروني",
      emailPh: "you@example.tn",
      subject: "طبيعة الملف",
      subjects: [
        "قانون الشركات / الأعمال",
        "الأحوال الشخصية / الأسرة",
        "العقار",
        "قانون الشغل",
        "الجزائي / الجرائم الاقتصادية",
        "استخلاص الديون / التنفيذ",
        "موضوع آخر",
      ],
      date: "التاريخ المرغوب",
      slot: "الوقت المرغوب",
      slots: ["صباحاً (8:30 — 12:00)", "بعد الزوال (13:30 — 17:30)", "هاتفياً", "مناظرة مرئية"],
      message: "رسالتكم",
      messagePh: "اعرضوا بإيجاز الوقائع والأطراف المعنية والإجراءات المنجزة والآجال المحتملة…",
      submit: "إرسال الطلب",
      whatsapp: "إرسال عبر واتساب",
      note: "تُعالَج معطياتكم بسرية تامة، ولا يُباشر أي إجراء قبل توقيع اتفاق الأتعاب.",
      required: "يرجى إدخال الاسم ووسيلة اتصال وعرض موجز للوضعية.",
      greeting: "تحية طيبة الأستاذ المحترم،",
      sending: "جارٍ الإرسال…",
      sentTitle: "تمّ إرسال طلبكم.",
      sentSub: "سيصلكم الرد داخل 24 ساعة عمل.",
      preparedTitle: "طلبكم جاهز للإرسال.",
      preparedSub: "لا يُفعَّل أي إرسال آلي في هذا الموقع: اختاروا القناة أدناه، ورسالتكم مُحرَّرة سلفاً.",
      networkError: "تعذّر الإرسال. تحقّقوا من الاتصال ثم أعيدوا المحاولة، أو استعملوا إحدى القنوات أدناه.",
      channelLabel: "اختيار قناة الإرسال",
      reopen: "إرسال طلب آخر",
      summaryTitle: "خلاصة الطلب",
    },
  },
  footer: {
    tagline: "مكتب محاماة مسجّل بالعمادة الوطنية للمحامين بتونس — استشارة وتفاوض ومرافعة أمام المحاكم التونسية.",
    navTitle: "التنقل",
    expertiseTitle: "المجالات",
    legalTitle: "معلومات",
    legal1: "المعلومات المنشورة في هذا الموقع عامة ولا تُعدّ استشارة قانونية.",
    legal2: "معطيات الاتصال للعرض فقط — يجب استبدالها بالمعلومات الرسمية للمكتب (الهيئة الوطنية للمحامين بتونس).",
    legal3: "الأرقام والشهادات المعروضة هنا إرشادية في هذه النسخة، وتُستكمل بوثائق المكتب قبل أي نشر علني.",
    rights: "جميع الحقوق محفوظة.",
    top: "أعلى الصفحة",
  },
  legal: {
    title: "التعريف القانوني وحماية المعطيات",
    editor: "ناشر الموقع",
    editorValue: "مكتب الأستاذ إبراهيم مجدوب، المحامي المسجّل بعمادة محامي تونس.",
    hosting: "الاستضافة",
    hostingValue: "تُحدَّد عند الدخول حيّز الإنتاج.",
    dataTitle: "المعطيات الشخصية",
    dataBody:
      "تُستعمل المعطيات المُدخلة في الاستمارة لإعداد طلبكم فقط: فلا يُخزّنها هذا الموقع ولا يُحيلها إلى الغير. وعملاً بالقانون الأساسي عدد 63 لسنة 2004 المتعلق بحماية المعطيات الشخصية، لكم حق النفاذ والتعديل والحذف بمخاطبة المكتب بإحدى قنوات الاتصال المذكورة أعلاه.",
    cookiesTitle: "الكوكيز (ملفّات تعريف الارتباط)",
    cookies:
      "لا يودع هذا الموقع أي كوكي لقياس الجمهور. الخريطة المضمّنة توفّرها خرائط جوجل وقد تطبّق قواعدها الخاصة في حماية الخصوصية.",
  },
};

export const content: Record<Lang, typeof fr> = { fr, en, ar };
